apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "togoservice"
  labels: 
    app: "togoservice"
spec: 
  selector: 
    matchLabels: 
      app: "togoservice"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "togoservice"
    spec: 
      containers: 
        - name: "gateway"
          image: "findjiwon/gateway:latest"
          ports: 
            - containerPort: 8088
        - name: "marketing"
          image: "findjiwon/marketing:latest"
          ports: 
            - containerPort: 8081
        - name: "order"
          image: "findjiwon/order:latest"
          ports: 
            - containerPort: 8082
        - name: "delivery"
          image: "findjiwon/delivery:latest"
          ports: 
            - containerPort: 8083
        - name: "dashboard"
          image: "findjiwon/dashboard:latest"
          ports: 
            - containerPort: 8085
